### ISSUE TITLE
Python 2 vs Python 3

### ISSUE THREAD

**Issue by davidfstr** [crista/exercises-in-programming-style#18]
All of the Python examples are written in Python 2 instead of Python 3. I think it would be a good idea to encourage the use of Python 3 in newly written materials given that Python 2 has been feature-frozen since July 2010. Python 3 is the future.

Did you have a specific reason around using Python 2?

**Comment by gqqnbig** [comment]
How about creating a new branch containing the 2to3 conversion? People using python 3 can checkout this branch.

**Comment by cclauss** [comment]
2to3 is really not advised.  It often breaks Python 2 compatibility to achieve Python 3 compatibility.  Consider futurize or modernize instead.

**Comment by jimmahoney** [comment]
It would be helpful to indicate which version(s) python your code has been tested on. This is my first time visiting, and I had to search for clues about python versions (i.e. looking for "print") before winding up here. Even given that your python is written for 2.*, there are differences between the versions.

**Comment by cclauss** [comment]
@jimmahoney look at #37 for Python 3 related modifications

**Comment by crista** [comment]
Good news! I'm finally porting the code to Python 3! It will happen over the next couple of weeks.

**Comment by davidfstr** [comment]
Glad to hear the examples are coming to Python 3!

For most code there shouldn't be much difference between Python 2 and 3. I'm guessing you'll just need to add ()s after your prints. And maybe open files slightly differently. But that's probably it. If you do it carefully, the code will work on both Python 2 and 3 without modification.

**Comment by cclauss** [comment]
https://github.com/crista/exercises-in-programming-style/pull/37/files

**Comment by crista** [comment]
Check out the latest commit -- EPC for Python 3 is here!
