### ISSUE TITLE
More programming languages

### ISSUE THREAD

**Issue by cies** [crista/exercises-in-programming-style#27]
I just saw yr talk of the JoC conference.

Now I found that the "pipeline" style comes in several languages but the other ones I checked out didn't.  Is there a reason for this?

For yr talk I learned you do assignments in a course you teach, where students pick a not-Python (maybe also non-Prolog???) language to "port" all the exercises to.

Would it be an idea to merge this project into the [Rosetta Stone](http://rosettacode.org/wiki/Rosetta_Code) of programming languages?  Your students probably already did most of the work already :)

**Comment by crista** [comment]
hi!

I started this repo with the idea of adding more examples in different programming languages as people would send them to me. However, I changed my mind. Here's why.

I teach a course based on these exercises, in which the students start by rewriting each of the styles in their favorite language. If I have the solutions here, the students will be robbed of the opportunity to do it themselves, which is a shame... the students asked me to stop accepting those kinds of contributions.
