### ISSUE TITLE
Need help with 'Good Old Times'

### ISSUE THREAD

**Issue by fahmad27** [crista/exercises-in-programming-style#28]
Okay, I am so utterly confused! I'm trying very hard to figure this lesson out and I felt like I haven't learned anything except how to put parentheses in 'print'. Here is what I am having trouble with:

1) How do you filter the characters in Part 1?
2) It says to read the input file. What input file? 
3) Another instruction says to find 25 frequency words in Part 2. What 25 frequency words?
4) How do you load the list of stop words?
5) How do you loop over the secondary memory file? 
6) When I ran the lesson in my Python program, the message said that the stop_words.txt is not found. How do I fix this?

**Comment by gvlx** [comment]
Is it a different file from the one on the root of the git respository? 
https://github.com/crista/exercises-in-programming-style/blob/master/stop_words.txt

**Comment by crista** [comment]
The input file is in the root folder:
https://github.com/crista/exercises-in-programming-style/blob/master/pride-and-prejudice.txt
So is the stopwords file, as pointed out by @gvlx
