### ISSUE TITLE
Meaning of "elimination of symbol c(or i, tf) is exercise" in  01-good-old-times

### ISSUE THREAD

**Issue by vics-kwon** [crista/exercises-in-programming-style#44]
https://github.com/crista/exercises-in-programming-style/blob/d521abd5d7aac14af19aa7794aca9ee23c0f8cc5/01-good-old-times/tf-01.py#L60

Does this sentence mean that we try to remove symbol c by applying other programming style (e.g., by using lambda expression)?

**Comment by crista** [comment]
It means you have to remove the symbol but sticking to the style. In this style, instead of symbols, you have pre-defined indexes into memory (in this case, the 'data' list)

**Comment by vics-kwon** [comment]
Thanks for your reply!
