### ISSUE TITLE
Trailing semicolon in the statement

### ISSUE THREAD

**Issue by marodev** [crista/exercises-in-programming-style#48]
What is the use of the trailing semicolon on line 69?

https://github.com/crista/exercises-in-programming-style/blob/88bb3ee2dfa6948101dec0589a15ec368be36506/06-pipeline/tf-06.py#L69

It seems to be useless and is not considered to be 'Pythonic' syntax. This was probably just copied from the book?

**Comment by crista** [comment]
fixed
