### ISSUE TITLE
34: "the C flow" name correct?

### ISSUE THREAD

**Issue by hparra** [crista/exercises-in-programming-style#9]
The constraints seem contrary to C-style programming. We love those early returns and efficient breaks, e.g. terminate a search loop.

I remember these constraints as a style called "single entry, single exit", with the additional constraint that there can only be a single return statement. This usually results in the possible return value being stored in a variable first.

Cool project. Good luck with the book.

**Comment by crista** [comment]
I haven't finished this style yet. The may be misleading. It's not about C, it's about control flow. Bad name.
